# Generated by Django 3.2.8 on 2021-11-11 23:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_product_offer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Category',
            field=models.CharField(choices=[('smartphone', 'smartphone'), ('MFashion', 'MFashion'), ('FFashion', 'FFashion'), ('Laptops', 'Laptops'), ('Headphones', 'Headphones'), ('Shoes', 'Shoes'), ('TV', 'TV'), ('electronics', 'electronics')], max_length=15),
        ),
        migrations.AlterField(
            model_name='product',
            name='Title',
            field=models.CharField(max_length=40),
        ),
        migrations.CreateModel(
            name='shirts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Brand', models.CharField(choices=[('AlS', 'allen solly'), ('PE', 'peter england'), ('PA', 'park avenue'), ('LP', 'louis philepe')], max_length=3)),
                ('Color', models.CharField(choices=[('red', 'red'), ('white', 'white'), ('black', 'black'), ('gray', 'gray'), ('blue', 'blue'), ('purple', 'purple'), ('green', 'green')], max_length=20)),
                ('Item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.product')),
            ],
        ),
        migrations.CreateModel(
            name='phones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Brand', models.CharField(choices=[('MI', 'mi'), ('IP', 'iphone'), ('OP', 'one plus'), ('SAM', 'samsung')], max_length=5)),
                ('color', models.CharField(choices=[('red', 'red'), ('white', 'white'), ('black', 'black'), ('gray', 'gray'), ('blue', 'blue'), ('purple', 'purple'), ('green', 'green')], max_length=20)),
                ('Ram', models.IntegerField()),
                ('Storage', models.CharField(choices=[('32 GB', '32 GB'), ('64GB', '64 GB'), ('128 GB', '128 GB'), ('256 GB', '256 GB'), ('512 GB', '512 GB'), ('1 TB', '1 TB')], max_length=6)),
                ('Item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.product')),
            ],
        ),
        migrations.CreateModel(
            name='laptops',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ram', models.IntegerField()),
                ('Brand', models.CharField(choices=[('hp', 'hp'), ('dell', 'dell'), ('apple', 'apple')], max_length=12)),
                ('Storage', models.CharField(choices=[('128 GB', '128 GB'), ('256 GB', '256 GB'), ('512 GB', '512 GB'), ('1 TB', '1 TB')], max_length=6)),
                ('Storage_type', models.CharField(choices=[('SSD', 'SSD'), ('HDD', 'HDD')], max_length=3)),
                ('Item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.product')),
            ],
        ),
    ]
