# Generated by Django 3.2.8 on 2021-11-23 11:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('App', '0004_phones_item_model'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Users',
            new_name='Customer',
        ),
        migrations.AlterField(
            model_name='product',
            name='Category',
            field=models.CharField(choices=[('smartphone', 'smartphone'), ('MFashion', 'MFashion'), ('shirt', 'shirt'), ('FFashion', 'FFashion'), ('Laptops', 'Laptops'), ('Headphones', 'Headphones'), ('Shoes', 'Shoes'), ('TV', 'TV'), ('electronics', 'electronics')], max_length=15),
        ),
    ]
