# Generated by Django 3.2.8 on 2021-12-02 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0007_alter_cart_qty'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='address',
        ),
    ]
